import type { Metadata } from "next";
import { Open_Sans, Inter } from 'next/font/google'
import "./globals.css";
import StoreProvider from "@/providers/StoreProvider";
import SessionProvider from './SessionProvider'

import { getServerSession } from "next-auth";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { authOptions } from "@/libs/auth";
import NextTopLoader from 'nextjs-toploader';
import { GoogleAnalytics } from '@next/third-parties/google'
import Script from "next/script";



import { redirect } from 'next/navigation';



const openSans = Open_Sans({
  weight: ["400", "500", "600", "700", "800"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-open",
})

const inter = Inter({
  weight: ["400", "500", "600", "700", '800'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const FB_PIXEL_ID = process.env.NEXT_PUBLIC_FACEBOOK_PIXEL_ID;


export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const session = await getServerSession(authOptions);


  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="WukHyBqs1sIjRy0uoRgOkoY-3clXUzFM5kfJaRSQiZY" />
        <meta name="robots" content="noindex, nofollow" />
        <Script
          id="sitebehaviour-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  if (
                    window.location &&
                    window.location.search &&
                    window.location.search.indexOf('capture-sitebehaviour-heatmap') !== -1
                  ) {
                    sessionStorage.setItem('capture-sitebehaviour-heatmap', '_');
                  }

                  var sbSiteSecret = 'beaca5f0-8a82-4d38-aeae-55982eb881cb';
                  window.sitebehaviourTrackingSecret = sbSiteSecret;

                  var scriptElement = document.createElement('script');
                  scriptElement.defer = true;
                  scriptElement.id = 'site-behaviour-script-v2';
                  scriptElement.src =
                    'https://sitebehaviour-cdn.fra1.cdn.digitaloceanspaces.com/index.min.js?sitebehaviour-secret=' +
                    sbSiteSecret;

                  document.head.appendChild(scriptElement);
                } catch (e) {
                  console.error(e);
                }
              })();
            `,
          }}
        />
        {/* Facebook Pixel */}
        <Script
          id="facebook-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod ?
              n.callMethod.apply(n, arguments) : n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');

              fbq('init', '${FB_PIXEL_ID}');
              fbq('track', 'PageView');
            `,
          }}
        />
      </head>
      <body
        className={`${openSans.variable} ${inter.variable} antialiased`}
      >
        <NextTopLoader
          color="#ad54f2"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={4000}
        />
        <ToastContainer
          style={{ zIndex: "9999" }}
        />

        {/* Facebook Pixel NoScript */}
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src={`https://www.facebook.com/tr?id=${FB_PIXEL_ID}&ev=PageView&noscript=1`}
          />
        </noscript>

        <SessionProvider session={session} refetchInterval={1 * 60}>
          <StoreProvider>
            {children}
          </StoreProvider>
        </SessionProvider>
        <GoogleAnalytics gaId="G-R45FZ1KSKT" />
      </body>
    </html>
  );
}