import type { Metadata } from "next";
import { Open_Sans, Inter } from 'next/font/google'
import "./globals.css";
import StoreProvider from "@/providers/StoreProvider";

const openSans = Open_Sans({
  weight: ["400", "500", "600", "700","800"],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-open",
})

const inter = Inter({
  weight: ["400", "500", "600", "700",'800'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${inter.variable} antialiased`}
      >
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
