import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import "./globals.css";
import Header from "@/components/header-footer/Header";
import Footer from "@/components/header-footer/Footer";
import StoreProvider from "@/providers/StoreProvider";

const openSans = Open_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-open-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased`}
      >
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
